[[repos]]
url = "https://raw.githubusercontent.com/leftwm/leftwm-community-themes/master/known.toml"
name = "community"
definitions_version = 1
themes = []

[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 1
themes = []
