[colors.primary]
background = "#1e1e1e"
foreground = "#d4d4d4"

[colors.cursor]
text = "#d4d4d4"
cursor = "#d4d4d4"

[colors.normal]
black = "#1e1e1e"
red = "#f44747"
green = "#608b4e"
yellow = "#dcdcaa"
blue = "#569cd6"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#d4d4d4"

[colors.bright]
black = "#545454"
red = "#f44747"
green = "#608b4e"
yellow = "#dcdcaa"
blue = "#569cd6"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#d4d4d4"

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "alacritty"

[font]
size = 14

[font.normal]
family = "Comic Shanns"

[window]
opacity = 0.9
